package com.sihai.pojo;

import java.util.Date;

public class Menu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.MENU_ID
     *
     * @mbg.generated
     */
    private Long menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.MENU_CATALOG_ID
     *
     * @mbg.generated
     */
    private Integer menuCatalogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.MENU_NAME
     *
     * @mbg.generated
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.MENU_CODE
     *
     * @mbg.generated
     */
    private String menuCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.MENU_DESC
     *
     * @mbg.generated
     */
    private String menuDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.MENU_URL
     *
     * @mbg.generated
     */
    private String menuUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.STS
     *
     * @mbg.generated
     */
    private String sts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.STS_DATE
     *
     * @mbg.generated
     */
    private Date stsDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.CREATE_DATE
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.ORDER_NO
     *
     * @mbg.generated
     */
    private Long orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.IMG_URL
     *
     * @mbg.generated
     */
    private String imgUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.MENU_ID
     *
     * @return the value of menu.MENU_ID
     *
     * @mbg.generated
     */
    public Long getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.MENU_ID
     *
     * @param menuId the value for menu.MENU_ID
     *
     * @mbg.generated
     */
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.MENU_CATALOG_ID
     *
     * @return the value of menu.MENU_CATALOG_ID
     *
     * @mbg.generated
     */
    public Integer getMenuCatalogId() {
        return menuCatalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.MENU_CATALOG_ID
     *
     * @param menuCatalogId the value for menu.MENU_CATALOG_ID
     *
     * @mbg.generated
     */
    public void setMenuCatalogId(Integer menuCatalogId) {
        this.menuCatalogId = menuCatalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.MENU_NAME
     *
     * @return the value of menu.MENU_NAME
     *
     * @mbg.generated
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.MENU_NAME
     *
     * @param menuName the value for menu.MENU_NAME
     *
     * @mbg.generated
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.MENU_CODE
     *
     * @return the value of menu.MENU_CODE
     *
     * @mbg.generated
     */
    public String getMenuCode() {
        return menuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.MENU_CODE
     *
     * @param menuCode the value for menu.MENU_CODE
     *
     * @mbg.generated
     */
    public void setMenuCode(String menuCode) {
        this.menuCode = menuCode == null ? null : menuCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.MENU_DESC
     *
     * @return the value of menu.MENU_DESC
     *
     * @mbg.generated
     */
    public String getMenuDesc() {
        return menuDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.MENU_DESC
     *
     * @param menuDesc the value for menu.MENU_DESC
     *
     * @mbg.generated
     */
    public void setMenuDesc(String menuDesc) {
        this.menuDesc = menuDesc == null ? null : menuDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.MENU_URL
     *
     * @return the value of menu.MENU_URL
     *
     * @mbg.generated
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.MENU_URL
     *
     * @param menuUrl the value for menu.MENU_URL
     *
     * @mbg.generated
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl == null ? null : menuUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.STS
     *
     * @return the value of menu.STS
     *
     * @mbg.generated
     */
    public String getSts() {
        return sts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.STS
     *
     * @param sts the value for menu.STS
     *
     * @mbg.generated
     */
    public void setSts(String sts) {
        this.sts = sts == null ? null : sts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.STS_DATE
     *
     * @return the value of menu.STS_DATE
     *
     * @mbg.generated
     */
    public Date getStsDate() {
        return stsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.STS_DATE
     *
     * @param stsDate the value for menu.STS_DATE
     *
     * @mbg.generated
     */
    public void setStsDate(Date stsDate) {
        this.stsDate = stsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.CREATE_DATE
     *
     * @return the value of menu.CREATE_DATE
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.CREATE_DATE
     *
     * @param createDate the value for menu.CREATE_DATE
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.ORDER_NO
     *
     * @return the value of menu.ORDER_NO
     *
     * @mbg.generated
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.ORDER_NO
     *
     * @param orderNo the value for menu.ORDER_NO
     *
     * @mbg.generated
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.IMG_URL
     *
     * @return the value of menu.IMG_URL
     *
     * @mbg.generated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.IMG_URL
     *
     * @param imgUrl the value for menu.IMG_URL
     *
     * @mbg.generated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }
}